apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-test2-hpa
  labels:
    app: nginx-test2
    version: 0.0.1
    backstage.io/kubernetes-id: nginx-test2
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: nginx-test2
 minReplicas: 1
 maxReplicas: 4
 targetCPUUtilizationPercentage: 75